# Generated by Django 3.1.1 on 2020-10-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueño', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=1000)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('costo', models.IntegerField()),
                ('estado', models.CharField(choices=[('cotizacion', 'cotizacion'), ('ejecucion', 'ejecucion'), ('terminada', 'termiada'), ('confirmada_veterinario', 'confirmada_veterinario')], max_length=30)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.mascota')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.promocion')),
                ('servicio_id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto')),
                ('promocion_id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.promocion')),
            ],
        ),
    ]
