# Generated by Django 3.1.2 on 2020-10-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tipomascota')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('dueño', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.raza')),
            ],
        ),
    ]
